-- AlterTable
ALTER TABLE "Recruitment" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "modifiedBy" TEXT NOT NULL DEFAULT 'SYSTEM',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT '1970-01-01 00:00:00 +00:00';

-- AlterTable
ALTER TABLE "Sponsor" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "modifiedBy" TEXT NOT NULL DEFAULT 'SYSTEM',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT '1970-01-01 00:00:00 +00:00';

-- AlterTable
ALTER TABLE "Timeline" ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "modifiedBy" TEXT NOT NULL DEFAULT 'SYSTEM',
ALTER COLUMN "updatedAt" SET DEFAULT '1970-01-01 00:00:00 +00:00';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "modifiedBy" TEXT NOT NULL DEFAULT 'SYSTEM',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT '1970-01-01 00:00:00 +00:00';
