import Head from "next/head";
import { memo } from "react";

import Footer from "@/components/Footer";
import HomePage from "@/components/homePage";

const Home = () => {
  return (
    <>
      <Head>
        <title>Calgary Solar Car</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main style={{ height: "100vh" }}>
        <HomePage />
      </main>
      <Footer />
    </>
  );
};

export default memo(Home);
